<form id="form1" name="form" method="post" action="<?php echo BASE_URL; ?>post/editar/<?php echo $this->datos['id']; ?>">
	<input type="hidden" name="guardar" value="1"/>
	<p>Título<br/>
	<input type="text" name="titulo" value="<?php if (isset($this->datos['titulo'])) echo$this->datos['titulo']; ?>" /></p>
	<p>Cuerpo del post<br/>
		<textarea name="cuerpo"><?php if (isset($this->datos['cuerpo'])) echo$this->datos['cuerpo']; ?></textarea>
	</p>
	<div>
		<input type="submit" value="Editar"/>
	</div>

</form>