<div class="row justify-content-center">
	<div class="col-6">
		<form id="form1" name="form" method="post" action="<?php echo BASE_URL; ?>post/nuevo">
			<input type="hidden" name="guardar" value="1"/>
			<div class="form-group">
				<label>Título</label>
				<input class="form-control"> type="text" name="titulo" value="<?php if (isset($this->datos['titulo'])) echo$this->datos['titulo']; ?>" />
			</div>
			<div class="form-group">
				<label>Cuerpo</label>
				<textarea class="form-control" name="cuerpo"><?php if (isset($this->datos['cuerpo'])) echo$this->datos['cuerpo']; ?></textarea>
			</div>
				<div>
					<input type="submit" value="Guardar"/>
				</div>

			</form>
		</div>
	</div>