<?php echo $this->titulo; ?>
<h2>Hola desde index</h2>

<?php if (isset($this->posts) && count($this->posts)): ?>

	<table border="1">
		<?php for ( $i = 0; $i < count($this->posts); $i++): ?>
			<tr>
				<td><?php echo $this->posts[$i]['id']; ?></td>
				<td><?php echo $this->posts[$i]['titulo']; ?></td>
				<td><?php echo $this->posts[$i]['cuerpo']; ?></td>
			</tr>
		<?php endfor; ?>
	</table>

<?php else: ?>
	<p><strong>No hay Posts...</strong></p>
<?php endif; ?>