<div class="col-12">
	<h2>Registro de Usuarios</h2>
	<form name="form" method="post">
		<input type="hidden" name="enviar" value="1">
		<div>
			<p>Nombre</p>
			<input type="text" name="nombre" value="<?php if(isset($this->datos)) echo $this->datos['nombre']; ?>">
		</div>
		<div>
			<p>Usuario</p>
			<input type="text" name="usuario" value="<?php if(isset($this->datos)) echo $this->datos['usuario']; ?>">
		</div>
		<div>
			<p>Email</p>
			<input type="text" name="email" value="<?php if(isset($this->datos)) echo $this->datos['email']; ?>">
		</div>
		<div>
			<p>Contraseña</p>
			<input type="password" name="pass">
		</div>
		<div>
			<p>Contraseña</p>
			<input type="password" name="confirmar">
		</div>
		<br>
		<div>
			<input type="submit" value="Enviar">
		</div>
	</form>
</div>